sudo: false
language: python
python:
- '2.7'

# These doesn't install on Travis right now!
#- '3.0'
#- '3.1'

- '3.2'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- nightly
install:
- if [[ $TRAVIS_PYTHON_VERSION > 3.2 ]]; then pip install -U pip virtualenv; fi
script:
- make test
- if [[ $TRAVIS_PYTHON_VERSION > 3.2 ]]; then make setup; source .venv/bin/activate; make check; fi
