language: python
python:
- '2.7'

# These doesn't install on Travis right now!
#- '3.0'
#- '3.1'
#- '3.2'
#- '3.3'

- '3.4'
- '3.5'
- '3.6'
- '3.7'
- '3.8'
- '3.9-dev'

install:
- misc/travis/install.sh

script:
- misc/travis/script.sh

after_success:
- misc/travis/after_success.sh
