language: python
python:
- '2.7'

# These doesn't install on Travis right now!
#- '3.0'
#- '3.1'
#- '3.2'
#- '3.3'

- '3.4'
- '3.5'
- '3.6'
- '3.7'
- '3.8'

install:
- pip install -U pip virtualenv
script:
- misc/travis.sh
after_success:
- if [[ $TRAVIS_PYTHON_VERSION != 3.2 && $TRAVIS_PYTHON_VERSION != 3.3 && $TRAVIS_PYTHON_VERSION != 3.4 ]]; then make coveralls; fi
