name: Analyze

# On all pushes to branches and pull requests in general.
on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  analyze:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']

    steps:
    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84
      with:
        path: ~/.cache/pip
        key: ${{ runner.os}}-pip-${{ hashFiles('**/.*-requirements.txt') }}
        restore-keys: |
          ${{ runner.os}}-pip-
    - name: Analyze
      run: ./misc/actions/analyze.sh
