name: Semgrep
on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - master
      - dev
    paths:
      - .github/workflows/semgrep.yml
  # Run every sunday at 3:12.
  schedule:
    - cron: '12 3 * * 6'
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        # It takes some time to scan "vermin/rules.py". More than the default 30s timeout.
      - run: semgrep ci --timeout 60 --verbose
