name: Snyk

# On all pushes/PRs.
on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  security:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        requirements: [misc, analysis, coverage]

    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Set up Python
        uses: actions/setup-python@13ae5bb136fac2878aff31522b9efb785519f984
        with:
          python-version: '3.10'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7
        with:
          path: ~/.cache/pip
          key: snyk-pip-${{ hashFiles('**/.*-requirements.txt') }}
          restore-keys: snyk-pip-

      - name: Upgrade Pip
        run: pip3 install --upgrade pip
      - name: Install requirements
        run: python3 -m pip install -r misc/.${{matrix.requirements}}-requirements.txt

      - name: Install Snyk
        run: npm install -g snyk
      - name: Run Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          FORCE_COLOR: 2
          SNYK_INTEGRATION_NAME: GITHUB_ACTIONS
          SNYK_INTEGRATION_VERSION: python
        run: snyk test --project-name=vermin --package-manager=pip --file=misc/.${{matrix.requirements}}-requirements.txt --command=python3 --show-vulnerable-paths=all --print-deps
